### ISSUE TITLE
Refresh Audio

### ISSUE THREAD

**Issue by johnroby** [emotionLoop/visualCaptcha-frontend-core#5]
Hi,
As I can refresh the audio without re-loading images. Namely,
When I'm the audio and I press refresh images show me again, how I can prevent this? If I press refresh audio, I want to reload the audio file no images
thanks

**Comment by BrunoBernardino** [comment]
Hi @johnroby the images and audio are refreshed together (as in, fetch new captcha options, not specifically audio or image).

In any case, if you're feeling adventurous, you should try to change the code to do what you want.

You'd have to send a new parameter (that would tell the back-end if you're refreshing for only audio, only images, or both), and change the back-end code to only refresh that one. The back-end module would have to be changed as well, because right now, all versions generate new captcha options, not independently.

Hope that helps!

**Comment by johnroby** [comment]
Thanks for the quick answer.
 
Sorry, I explained bad, right in what you say and that's fine. 
What I mean is that if I am in the validation of audio and  I click in audio refresh, the "captcha" remains in the audio validation and not go to the images validation. 
Because then I have to press audio icon to repeat the audio validation.

**Comment by BrunoBernardino** [comment]
That is not happening to me on http://demo.visualcaptcha.net/ is it happening to you there? With which browser?

**Comment by johnroby** [comment]
chrome and ie 11.

In fact , when I want to repeat the audio, it switch to the images, and I have to click again icon audio to repeat. It should function as other captchas , like google recaptcha for example. 
thanks for all the trouble.

**Comment by BrunoBernardino** [comment]
Ok, so you're asking for it to _not_ go into images again, but refresh and remain in the audio.

The reason why it does that is because the elements are replaced, so you do have to hear the audio again (hence clicking it), otherwise the solution would be to refresh and instantly play the audio, which is possible. I just don't think it's a better UX than the current one.

Anyway, if someone else agrees with you, they can comment here and we can revisit later.

Thanks!
